name: Prepare new release

on:
  workflow_dispatch:
    inputs:
      no-release:
        description: "Don't release"
        type: boolean
        default: false
      draft:
        description: "Draft release"
        type: boolean
        default: false
      serverBump:
        description: 'Bump server version'
        required: true
        default: 'false'
        type: choice
        options:
          - 'false'
          - minor
          - patch
      mobileBump:
        description: 'Bump mobile build number'
        required: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-root
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  bump_version:
    runs-on: ubuntu-latest

    outputs:
      ref: ${{ steps.push-tag.outputs.commit_long_sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for github-action-get-previous-tag

      - name: Install Poetry
        run: pipx install poetry

      - name: Bump version
        run: misc/release/pump-version.sh -s "${{ inputs.serverBump }}" -m "${{ inputs.mobileBump }}"

      - name: Commit and tag
        id: push-tag
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Alex The Bot
          author_email: alex.tran1502@gmail.com
          default_author: user_info
          message: 'Version ${{ env.IMMICH_VERSION }}'
          tag: ${{ env.IMMICH_VERSION }}
          push: true

  build_mobile:
    uses: ./.github/workflows/build-mobile.yml
    needs: bump_version
    secrets: inherit
    with:
      ref: ${{ needs.bump_version.outputs.ref }}

  prepare_release:
    runs-on: ubuntu-latest
    needs: build_mobile

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_RELEASE_TOKEN }}

      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: release-apk-signed

      - name: Create and Publish release
        id: create-publish-release
        uses: softprops/action-gh-release@v2
        with:
          draft: ${{ contains(inputs.draft, 'true') }}
          tag_name: ${{ env.IMMICH_VERSION }}
          generate_release_notes: true
          body: |
            immich ${{ env.IMMICH_VERSION }}

            This is a release supporting older devices.
          files: |
            *.apk
